site_name: Black-Hat-Zig
site_url: https://black-hat-zig.cx330.tw
repo_url: https://github.com/cx330blake/black-hat-zig
repo_name: CX330Blake/Black-Hat-Zig
theme:
    name: material
    favicon: assets/favicon.svg
    logo: assets/zig.svg
    icon:
        repo: fontawesome/brands/github
    features:
        - content.code.copy
        - content.code.annotation
        - search.share
        - search.highlight
        - search.suggest
        - content.code.select
        - navigation.path
        - navigation.footer
        - navigation.top
        - navigation.instant
        - navigation.instant.progress
        - navigation.tabs
        - navigation.tracking
        - navigation.instant
        - navigation.instant.prefetch
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: orange
          accent: deep orange
          toggle:
              icon: material/brightness-4
              name: Switch to dark mode

        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: orange
          accent: deep orange
          toggle:
              icon: material/brightness-7
              name: Switch to light mode

docs_dir: "src"
plugins:
    - search
    - awesome-nav
    - social
    # - privacy:
    #       links_attr_map:
    #           target: _blank

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - def_list
    - pymdownx.tasklist:
          custom_checkbox: true
    - mdx_truly_sane_lists
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
    - stylesheets/extra.css
    - stylesheets/dracula-code-theme.css

extra:
    consent:
        title: Cookie consent
        description: >-
            We use cookies to recognize your repeated visits and preferences, as well
            as to measure the effectiveness of our documentation and whether users
            find what they're searching for. With your consent, you're helping us to
            make our documentation better.
    analytics:
        provider: google
        property: G-CYTPQ2676T
