site_name: Black-Hat-Zig
site_url: https://black-hat-zig.cx330.tw
repo_url: https://github.com/cx330blake/black-hat-zig
repo_name: CX330Blake/Black-Hat-Zig
theme:
    name: material
    favicon: assets/zig.svg
    logo: assets/zig.svg
    icon:
        repo: fontawesome/brands/github
    features:
        - content.code.copy
        - content.code.annotation
        - search.highlight
        - search.suggest
        - content.code.select
        - navigation.footer
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: orange
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: orange
          toggle:
              icon: material/brightness-4
              name: Switch to light mode

docs_dir: "docs"

nav:
    - Introduction: index.md
    - Before We Start: prologue.md
    - Payload Placement:
          - .data Section: "Payload-Placement/dot_data.md"
          - .rdata Section: "Payload-Placement/dot_rdata.md"
          - .text Section: "Payload-Placement/dot_text.md"
          - .rsrc Section: "Payload-Placement/dot_rsrc.md"
    - Payload Obfuscation:
          - IP Address Obfuscation: "Payload-Obfuscation/ip_addr.md"
          - MAC Address Obfuscation: "Payload-Obfuscation/mac_addr.md"
          - UUID Obfuscation: "Payload-Obfuscation/uuid.md"
    - Payload Encryption:
          - XOR Encryption: "Payload-Encryption/xor.md"
          - RC4 Encryption: "Payload-Encryption/rc4.md"
          - AES Encryption: "Payload-Encryption/aes.md"
    - Payload Execution:
          - Execute Via DLL: "Payload-Execution/dll.md"
          - Execute Via Shellcode: "Payload-Execution/shellcode.md"
    - Malware Techniques:
          - Payload Staging:
                - Web Server: "Malware-Techniques/Payload-Staging/web_server.md"
                - Windows Registry: "Malware-Techniques/Payload-Staging/registry.md"
          - Process Injection:
                - DLL Injection: "Malware-Techniques/Process-Injection/dll_injection.md"
                - Shellcode Injection: "Malware-Techniques/Process-Injection/shellcode_injection.md"
          - Process Enumeration:
                - Using CreateToolhelp32Snapshot: "Malware-Techniques/Process-Enumeration/create_tool_help_32_snapshot.md"
                - Using EnumProcesses: "Malware-Techniques/Process-Enumeration/enum_processes.md"
                - Using NtQuerySystemInformation: "Malware-Techniques/Process-Enumeration/nt_query_system_information.md"
          # - Thread Hijacking:
    - Reverse Shell:
          - Reverse Shell With Standard Library: "Reverse-Shell/std_reverse_shell.md"
    - Epilogue: epilogue.md

plugins:
    - search
    - social
    - privacy:
          links_attr_map:
              target: _blank

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - def_list
    - pymdownx.tasklist:
          custom_checkbox: true
    - mdx_truly_sane_lists
