site_name: Black-Hat-Zig
site_url: https://black-hat-zig.cx330.tw
repo_url: https://github.com/cx330blake/black-hat-zig
repo_name: CX330Blake/Black-Hat-Zig
theme:
    name: material
    favicon: assets/zig.svg
    logo: assets/zig.svg
    icon:
        repo: fontawesome/brands/github
    features:
        - content.code.copy
        - content.code.annotation
        - search.highlight
        - search.suggest
        - content.code.select
        - navigation.footer
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: orange
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: orange
          toggle:
              icon: material/brightness-4
              name: Switch to light mode

docs_dir: "src"
plugins:
    - search
    - social
    - privacy:
          links_attr_map:
              target: _blank

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - def_list
    - pymdownx.tasklist:
          custom_checkbox: true
    - mdx_truly_sane_lists
