nav:
    - Get Started:
          - ./index.md
          - ./prologue.md
    - Basic Payload Management:
          - Payload Placement:
                - ./Basic-Payload-Management/Payload-Placement/dot_data.md
                - ./Basic-Payload-Management/Payload-Placement/dot_rdata.md
                - ./Basic-Payload-Management/Payload-Placement/dot_text.md
                - ./Basic-Payload-Management/Payload-Placement/dot_rsrc.md
          - ./Basic-Payload-Management/Payload-Obfuscation/
          - Payload Encryption:
                - ./Basic-Payload-Management/Payload-Encryption/XOR.md
                - ./Basic-Payload-Management/Payload-Encryption/RC4.md
                - ./Basic-Payload-Management/Payload-Encryption/AES.md
          - ./Basic-Payload-Management/Payload-Execution/
    - Advanced Malware Techniques:
          - ./Advanced-Malware-Techniques/Process-Injection/
          - ./Advanced-Malware-Techniques/Payload-Staging/
          - ./Advanced-Malware-Techniques/Process-Enumeration/
          - ./Advanced-Malware-Techniques/Callback-Code-Execution/callback_code_execution.md
    - Malware Examples:
          - ./Malware-Examples/Reverse-Shell/
    - Epilogue: ./epilogue.md
