nav:
    - Get Started:
          - ./index.md
          - ./prologue.md
    - Payload Management:
          - ./Payload-Placement
          - ./Payload-Obfuscation/
          - ./Payload-Encryption/
          - ./Payload-Execution/
    - Malware Techniques:
          - ./Malware-Techniques/*
    - Malware Examples:
          - ./Reverse-Shell/
    - Epilogue: ./epilogue.md
